name: CI

on: [push]

jobs :
  sast_scan: 
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set Up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Bandit 
      run: pip install bandit 
    - name: Run Bandit  Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
        
  image_scan: 
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Set Up Docker
      uses: docker/setup-docker-action@v5.3.0
      
    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    
    - name: Docker Scout Scan
      uses: ocker/scout-action@v1.23.1
     with:
       dockerhub-user: ${{ secrets.REPO_USER }}
       dockerhub-password: ${{ secrets.REPO_PWD }}
       command: quickview,cves
       only-severities: critical,high
       sarif-file: scout-report.sarif
       
    - name: Upload Artifact Docker Scout
     uses: actions/upload-artifact@v7.0.1
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif
  

    

       
